"""Check that Table 6's bold marks are the ones its caption's rule selects.

    python3 tools/check_table_marks.py

Most tables in this paper are generated by `src/tables.py`. Table 6 is not: it was
merged by hand from three per-arm tables when the tables were numbered, and a
hand-merged table carries its emphasis by hand too.

That is how it went wrong. The caption said bold marked a value Platt recalibration
moved below the class-prior **Brier** reference. The Arm A rows instead bolded the
**ECE + Platt** column -- including the CNN, whose raw Brier was already below the
reference, so the rule selected nothing for it -- and left unbolded the two Arm A
Brier cells the rule does select. Arms B and C bolded both columns. The same mark
meant three different things in one table, and one of them was an ECE value marked
against a Brier-scale reference, which is not a comparison that exists.

Nothing checked it, because the numbers were all correct: `src/scan.py` reads values
and cannot see which of them are wrapped in asterisks. This does.

It reads the table out of the manuscript, recomputes the rule from
`results/<arm>/calibration_summary.csv`, and compares the two sets of cells. It does
not care what the values are -- `scan.py` already owns that -- only which of them
are marked, and where.
"""

import os
import re
import sys

import pandas as pd

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)
import config as C  # noqa: E402

RESULTS = os.path.join(HERE, "manuscript", "RESULTS.md")
# On 30 September 2026 the three expected-calibration-error columns moved to
# Supplementary Table S4, so the article's Table 6 is five columns wide. The marked
# column is unchanged -- it is still Brier + Platt, and it is still in the article,
# which is why this check still belongs to the article and not to the supplement.
COLUMNS = ["Arm", "Model", "Brier raw", "Brier + Platt", "Brier + isotonic"]
HEADER = "| " + " | ".join(COLUMNS) + " |"
# Column index of the cell the rule may mark, counting from the "Arm" column.
BRIER_PLATT = COLUMNS.index("Brier + Platt")
BOLD = re.compile(r"^\*\*(.+)\*\*$")


def table_rows(text):
    """The data rows of Table 6, each as a list of raw cell strings."""
    if HEADER not in text:
        return None
    body = text[text.index(HEADER):].splitlines()
    rows = []
    for line in body[2:]:                       # skip header and separator
        line = line.strip()
        if not line.startswith("|"):
            break
        rows.append([c.strip() for c in line.strip("|").split("|")])
    return rows


def rule_selects():
    """(arm, model) pairs the caption's rule marks, from the released summaries."""
    out = set()
    for arm in sorted(C.ARMS):
        path = os.path.join(HERE, "results", arm, "calibration_summary.csv")
        if not os.path.exists(path):
            continue
        spec = C.ARMS[arm]
        pi = spec["n_drowsy"] / spec["n_windows"]
        ref = round(pi * (1 - pi), 4)
        for r in pd.read_csv(path).itertuples():
            if r.brier_raw > ref and r.brier_platt < ref:
                out.add((arm, r.model))
    return out


# Table 6 is checked against its rule cell by cell, because its rule is specific
# enough to evaluate. The tables below get the weaker, general check: a caption that
# states a bold rule must have bold cells, and bold cells must have a stated rule.
# That is all it takes to catch the two defects that got through -- Table 5, whose
# caption said "Bold marks a score above the reference" over a table with no bold in
# it at all, and Table 4, which bolded one cell and stated no rule.
CAPTION = re.compile(r"^\*\*Table (\d+)\.")
RULE_WORDS = re.compile(r"\bbold\b", re.I)


def _tables_with_captions(text):
    """(number, caption text, [data rows]) for every captioned table in the file."""
    lines = text.splitlines()
    out = []
    for i, line in enumerate(lines):
        m = CAPTION.match(line.strip())
        if not m:
            continue
        caption, j = [], i
        while j < len(lines) and not lines[j].strip().startswith("|"):
            caption.append(lines[j])
            j += 1
        rows = []
        for k in range(j + 2, len(lines)):       # skip header and separator
            if not lines[k].strip().startswith("|"):
                break
            rows.append([c.strip() for c in lines[k].strip().strip("|").split("|")])
        out.append((int(m.group(1)), "\n".join(caption), rows))
    return out


def check_every_captioned_table(text):
    """A stated rule needs marks; marks need a stated rule."""
    problems = []
    print("\nEvery captioned table: does its emphasis match what its caption says?\n")
    for number, caption, rows in _tables_with_captions(text):
        bold = sum(1 for r in rows for c in r if BOLD.match(c))
        states = bool(RULE_WORDS.search(caption))
        verdict = "ok"
        if states and not bold:
            verdict = "CAPTION STATES A BOLD RULE BUT NO CELL IS BOLD"
            problems.append("Table %d: %s" % (number, verdict))
        elif bold and not states:
            verdict = "CELLS ARE BOLD BUT THE CAPTION STATES NO RULE"
            problems.append("Table %d: %s" % (number, verdict))
        print("  Table %-2d  %2d bold cell(s), caption %s   %s"
              % (number, bold,
                 "states a rule   " if states else "states no rule",
                 verdict))
    return problems


def main():
    with open(RESULTS) as fh:
        text = fh.read()
    rows = table_rows(text)
    if not rows:
        print("Table 6 not found in manuscript/RESULTS.md -- has its header changed?")
        return 2

    marked, misplaced = set(), []
    for cells in rows:
        arm = BOLD.match(cells[0]).group(1) if BOLD.match(cells[0]) else cells[0]
        model = cells[1]
        for i, cell in enumerate(cells):
            if i < 2 or not BOLD.match(cell):
                continue
            if i == BRIER_PLATT:
                marked.add((arm, model))
            else:
                misplaced.append((arm, model, COLUMNS[i], BOLD.match(cell).group(1)))

    want = rule_selects()
    missing = sorted(want - marked)
    extra = sorted(marked - want)

    print("Table 6: bold marks against the rule its caption states\n")
    print("  rule selects   %d cell(s)" % len(want))
    print("  table marks    %d cell(s) in Brier + Platt" % len(marked))
    for arm, model, column, value in misplaced:
        print("  MARKED IN THE WRONG COLUMN  Arm %s %s: %s = %s"
              % (arm, model, column, value))
    for arm, model in missing:
        print("  RULE SELECTS BUT NOT MARKED  Arm %s %s" % (arm, model))
    for arm, model in extra:
        print("  MARKED BUT RULE DOES NOT SELECT  Arm %s %s" % (arm, model))

    general = check_every_captioned_table(text)
    for problem in general:
        print("  " + problem)

    bad = len(misplaced) + len(missing) + len(extra) + len(general)
    print("\n%d discrepancy(ies) between the marks and the rule" % bad)
    if not bad:
        print("Every bold cell is one the caption's rule selects, and every cell it "
              "selects is\nbold. No mark sits outside the Brier + Platt column.")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
