"""Build one audit snapshot: everything a reviewer needs, from one state of the repo.

    python3 tools/snapshot.py [--out DIR]

Why this is a script and not a list of copy commands. Six snapshots were assembled by
hand between 24 and 25 September 2026, and every one of them was missing something
the audit of it then needed. The first had a Figure 2 and a registry from different
days, which produced two false findings. A later one left out `src/models.py`, so an
independent check of the parameter counts had to work from the layers as described in
the prose rather than as built in the code -- and came out 4,096 high. The next left
out `tools/master_file.py` and the tests, so the generator that had just been
corrected could not be read.

Curating a bundle by hand is the same failure as typing a number by hand. This builds
it from the declared list below, stamps it with the manuscript's own build id, and
captures that build's preflight and test output rather than quoting them from memory.

What goes in, and why:

  manuscript/   the assembled paper, the generated master file, the status page, and
                the audit history -- the last clearly marked as history
  results/      the registry and every released table the paper's numbers come from
  figures/      all seven figures and the provenance listing
  src/          the pipeline. A claim about a number cannot be checked without it
  tools/        the checks and the generators. A claim about a CHECK cannot be
                checked without it
  tests/        what the suite actually asserts, not only that it passed
  PREFLIGHT.txt, TESTS.txt   this build's own output, captured here
  MANIFEST.txt  the build id, and the three-step test for whether a copy belongs

The raw recordings are not included and are not redistributable; results/README.md
says which counts that makes independently checkable and which it does not.
"""

import argparse
import datetime
import csv
import hashlib
import os
import re
import shutil
import subprocess
import sys
import zipfile

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)
import config as C  # noqa: E402
sys.path.insert(0, os.path.join(HERE, "tools"))
import build_manuscript as bm  # noqa: E402

# Directories copied whole, and the file patterns kept from each.
TREES = [
    ("src", (".py",)),
    ("tools", (".py", ".json")),
    ("tests", (".py",)),
    ("manuscript/audit-history", (".md",)),
]
# The manuscript sources, asked of the builder rather than listed again -- the same
# authoritative answer preflight uses. Without these the bundle carries the assembled
# paper but not what it was assembled from, and a check that reads a section file
# cannot run inside the snapshot that ships it.
_SECTION_SOURCES = ["manuscript/" + n for n in bm.SECTION_FILES]

# Individual files, by path relative to the repository root.
FILES = _SECTION_SOURCES + [
    "config.py", "run_all.py", "requirements.txt", "README.md",
    # Read by tools/check_submission_ready.py. Without them it reports every item
    # PENDING from inside the snapshot, which says nothing about the repository.
    "LICENSE", "CITATION.cff",
    # Read by tools/check_withdrawn.py.
    "manuscript/WITHDRAWN.md",
    "results/README.md",
    "manuscript/MANUSCRIPT.md", "manuscript/MASTER_FILE.md",
    "manuscript/REPRODUCIBILITY.md", "manuscript/DECISION_SHEET.md",
    # Generated by tools/check_split_map.py from tools/split_map.json. Included
    # because "why is this section not in the article?" is a question an auditor of
    # the submitted paper will ask, and the answer must travel with the bundle.
    "manuscript/SPLIT_MAP.md",
    # The second half of the submitted record. Moved out of the article on
    # 30 September 2026, not deleted; an audit of the paper needs both.
    "manuscript/SUPPLEMENTARY.md",
    "results/MASTER_NUMBERS.csv", "results/MULTIPLICITY.csv",
    "results/LITERATURE_NUMBERS.csv", "results/ALL_FOLDS.csv",
    "results/ALL_POOLED.csv", "results/ranking_invariance.csv",
    "figures/PROVENANCE.txt",
]
FIGURE_GLOB = re.compile(r"^figure[0-9S].*\.png$")


def build_id():
    """The manuscript's own stamp. If it is missing, the manuscript was not built."""
    path = os.path.join(HERE, "manuscript", "MANUSCRIPT.md")
    m = re.search(r"\*Build ([0-9a-f]+) ", open(path).read())
    if not m:
        raise SystemExit("MANUSCRIPT.md carries no build stamp; run the builder first")
    return m.group(1)


def registry_rows():
    with open(C.REGISTRY_CSV) as fh:
        return sum(1 for _ in csv.DictReader(fh))


def collect(dest):
    """Copy the declared set into dest, returning what was taken."""
    taken = []
    for tree, suffixes in TREES:
        src = os.path.join(HERE, tree)
        if not os.path.isdir(src):
            continue
        for name in sorted(os.listdir(src)):
            if not name.endswith(suffixes):
                continue
            out = os.path.join(dest, tree, name)
            os.makedirs(os.path.dirname(out), exist_ok=True)
            shutil.copy2(os.path.join(src, name), out)
            taken.append(os.path.join(tree, name))
    for rel in FILES:
        src = os.path.join(HERE, rel)
        if not os.path.exists(src):
            print("  MISSING, not copied: %s" % rel)
            continue
        out = os.path.join(dest, rel)
        os.makedirs(os.path.dirname(out), exist_ok=True)
        shutil.copy2(src, out)
        taken.append(rel)
    figs = os.path.join(HERE, "figures")
    for name in sorted(os.listdir(figs)):
        if FIGURE_GLOB.match(name):
            shutil.copy2(os.path.join(figs, name),
                         os.path.join(dest, "figures", name))
            taken.append(os.path.join("figures", name))
    return taken


def snapshot_digest(stage):
    """A digest over everything packed, so the bundle has an identity of its own.

    The build id belongs to the manuscript and does not move when a tool, a test or
    this script changes -- which is right for the paper and wrong for the bundle:
    two snapshots with the same build id and different contents is the ambiguity the
    build id exists to prevent, reappearing one level up.
    """
    h = hashlib.sha256()
    for root, dirs, names in os.walk(stage):
        dirs.sort()
        for name in sorted(names):
            if name == "MANIFEST.txt":
                continue                       # it is about to contain this digest
            full = os.path.join(root, name)
            h.update(os.path.relpath(full, stage).encode("utf-8"))
            with open(full, "rb") as fh:
                h.update(fh.read())
    return h.hexdigest()[:12]


def capture(dest):
    """This build's own verification output, run now rather than remembered."""
    for name, cmd in (("PREFLIGHT.txt", [sys.executable, "tools/preflight.py"]),
                      ("TESTS.txt", [sys.executable, "-m", "pytest", "tests/",
                                     "-q", "-rs"])):
        p = subprocess.run(cmd, cwd=HERE, capture_output=True, text=True)
        with open(os.path.join(dest, name), "w") as fh:
            fh.write(p.stdout + p.stderr)


MANIFEST = """Snapshot of eeg-drowsiness-loso
BUILD ID:     %(build)s     identifies the MANUSCRIPT
SNAPSHOT ID:  %(digest)s     identifies THIS BUNDLE
Snapshot date: %(date)s
Registry: %(rows)d rows
Files: %(count)d

The two are not the same thing and the difference matters. The build id is a digest
of the assembled manuscript body, so it stays put when something outside the paper
changes -- a check, a test, this script. Two bundles can therefore carry one build id
and different contents, which is exactly the ambiguity the build id was introduced to
remove. The snapshot id is a digest of every file packed here, so it changes whenever
anything in the bundle does. Cite the build id when you mean the paper; cite the
snapshot id when you mean the set of files you audited.

Built by tools/snapshot.py from one state of the repository. Earlier snapshots were
assembled by hand and each was missing something the audit of it then needed; that is
what this script exists to stop.

Does a copy belong to this set? Check in order:
  1. manuscript/MANUSCRIPT.md ends with  "Build %(build)s"
  2. that same stamp says "registry %(rows)d rows"
  3. results/MASTER_NUMBERS.csv has a row "rows in MASTER_NUMBERS.csv" = %(rows)d
If the three disagree, the copy is out of snapshot. Do not audit it. Those three
settle the manuscript; the snapshot id above settles the bundle.

PREFLIGHT.txt and TESTS.txt are this build's own output, captured when the snapshot
was made. src/, tools/ and tests/ are included so that a claim about a number, about
a check, or about what the suite asserts can each be read at its source rather than
taken on report.

manuscript/audit-history/ is a record of past audits. It is not current status; its
README says where current status lives.

The raw EEG recordings are not here and are not redistributed. results/README.md
states which window counts that leaves independently checkable (Arm B) and which it
does not (Arms A and C).
"""


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=None, help="directory to write the zip into")
    a = ap.parse_args(argv)

    build = build_id()
    out_dir = a.out or os.path.join(HERE, "snapshots")
    os.makedirs(out_dir, exist_ok=True)
    stage = os.path.join(out_dir, "snapshot")
    if os.path.isdir(stage):
        shutil.rmtree(stage)
    os.makedirs(stage)

    taken = collect(stage)
    capture(stage)
    rows = registry_rows()
    digest = snapshot_digest(stage)
    with open(os.path.join(stage, "MANIFEST.txt"), "w") as fh:
        fh.write(MANIFEST % dict(build=build, rows=rows, count=len(taken) + 3,
                                 digest=digest,
                                 date=datetime.date.today().isoformat()))

    # Named by BOTH ids: two bundles from one build id would otherwise overwrite
    # each other, which is the ambiguity the build id exists to prevent.
    zip_path = os.path.join(out_dir, "snapshot_%s_%s.zip" % (build, digest))
    if os.path.exists(zip_path):
        os.remove(zip_path)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for root, _dirs, names in os.walk(stage):
            for name in names:
                full = os.path.join(root, name)
                z.write(full, os.path.join("snapshot",
                                           os.path.relpath(full, stage)))
    shutil.rmtree(stage)
    print("wrote %s" % zip_path)
    print("  build %s (the manuscript), snapshot %s (this bundle)" % (build, digest))
    print("  registry %d rows, %d file(s)" % (rows, len(taken) + 3))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
